-- Fase 8: Cache local de cultivares RNC para consulta estável no app
-- Data: 2026-02-22

CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Fallback para ambientes em que a função ainda não existe.
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE TABLE IF NOT EXISTS public.rnc_cultivars_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rnc_uid TEXT NOT NULL UNIQUE,
  especie_nome_comum TEXT NOT NULL DEFAULT '',
  especie_nome_cientifico TEXT NOT NULL DEFAULT '',
  cultivar TEXT NOT NULL DEFAULT '',
  tipo_registro TEXT NOT NULL DEFAULT 'CULTIVAR',
  grupo_especie TEXT NOT NULL DEFAULT '',
  situacao TEXT NOT NULL DEFAULT '',
  numero_registro TEXT NOT NULL DEFAULT '',
  rnc_codsr TEXT,
  rnc_codverif TEXT,
  rnc_detail_url TEXT,
  sync_batch_id TEXT NOT NULL DEFAULT '',
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public' AND indexname = 'rnc_cultivars_cache_grupo_idx'
  ) THEN
    CREATE INDEX rnc_cultivars_cache_grupo_idx
      ON public.rnc_cultivars_cache (grupo_especie);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public' AND indexname = 'rnc_cultivars_cache_sync_batch_idx'
  ) THEN
    CREATE INDEX rnc_cultivars_cache_sync_batch_idx
      ON public.rnc_cultivars_cache (sync_batch_id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public' AND indexname = 'rnc_cultivars_cache_cultivar_trgm_idx'
  ) THEN
    CREATE INDEX rnc_cultivars_cache_cultivar_trgm_idx
      ON public.rnc_cultivars_cache USING gin (cultivar gin_trgm_ops);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public' AND indexname = 'rnc_cultivars_cache_nome_comum_trgm_idx'
  ) THEN
    CREATE INDEX rnc_cultivars_cache_nome_comum_trgm_idx
      ON public.rnc_cultivars_cache USING gin (especie_nome_comum gin_trgm_ops);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public' AND indexname = 'rnc_cultivars_cache_nome_cientifico_trgm_idx'
  ) THEN
    CREATE INDEX rnc_cultivars_cache_nome_cientifico_trgm_idx
      ON public.rnc_cultivars_cache USING gin (especie_nome_cientifico gin_trgm_ops);
  END IF;
END$$;

DROP TRIGGER IF EXISTS update_rnc_cultivars_cache_updated_at
  ON public.rnc_cultivars_cache;
CREATE TRIGGER update_rnc_cultivars_cache_updated_at
BEFORE UPDATE ON public.rnc_cultivars_cache
FOR EACH ROW
EXECUTE PROCEDURE public.update_updated_at_column();

ALTER TABLE public.rnc_cultivars_cache ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'rnc_cultivars_cache'
      AND policyname = 'Authenticated can read rnc cultivars cache'
  ) THEN
    CREATE POLICY "Authenticated can read rnc cultivars cache"
      ON public.rnc_cultivars_cache
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END$$;
